name: bupt_auth_dart
description: dart implementation of bupt-auth
version: 1.0.0
homepage: https://github.com/Shxuuer/bupt-auth-dart

environment:
  sdk: ^3.8.1

dependencies:
  http: ^0.13.6

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
